import { useMutation } from '@tanstack/react-query'
import { BrainCircuit, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api'
import { Card, PageHeader, PanelHeader, Toast } from '../components/UI'

export function AIResearch() {
  const [form, setForm] = useState({ symbol: '600036', action: 'BUY', score: 82, rank: 3, industry: '银行', volatility: .23, max_drawdown: .18, target_weight: .15, use_llm: false })
  const [result, setResult] = useState<any>(null)
  const mutation = useMutation({ mutationFn: async () => (await api.post('/ai/explain/trade', form)).data, onSuccess: setResult })
  return <><PageHeader eyebrow="INTELLIGENCE / 07" title="AI 投研助手" description="解释量化引擎为什么产生信号，但不替代 Quant Engine 做交易决定。" actions={<span className="ai-mode"><Sparkles size={15}/>规则解释器 · 无需 API Key</span>} /><div className="ai-layout"><Card><PanelHeader title="交易上下文" subtitle="输入一笔信号，生成可追溯解释"/><div className="form-grid"><label>股票代码<input value={form.symbol} onChange={e => setForm({...form, symbol: e.target.value})}/></label><label>交易方向<select value={form.action} onChange={e => setForm({...form, action: e.target.value})}><option>BUY</option><option>HOLD</option><option>SELL</option></select></label><label>综合评分<input type="number" value={form.score} onChange={e => setForm({...form, score: Number(e.target.value)})}/></label><label>排名<input type="number" value={form.rank} onChange={e => setForm({...form, rank: Number(e.target.value)})}/></label><label>所属行业<input value={form.industry} onChange={e => setForm({...form, industry: e.target.value})}/></label><label>目标权重<div className="input-with-suffix"><input type="number" value={form.target_weight * 100} onChange={e => setForm({...form, target_weight: Number(e.target.value) / 100})}/><span>%</span></div></label></div><button className="primary-button full-button" onClick={() => mutation.mutate()} disabled={mutation.isPending}><BrainCircuit size={16}/>{mutation.isPending ? '正在分析…' : '生成交易解释'}</button></Card><Card className="ai-result-card"><PanelHeader title="研究结论" subtitle="规则驱动 · 可审计"/>{result ? <div className="ai-result"><div className="ai-headline"><div className="ai-orb"><BrainCircuit/></div><div><span>QUANT EXPLANATION</span><h3>{result.headline}</h3></div></div><p>{result.content}</p><div className="risk-box"><b>风险提示</b>{result.risks.map((risk: string) => <span key={risk}>• {risk}</span>)}</div><div className="provider-line"><span>解释来源</span><b>{result.provider}</b></div></div> : <div className="ai-placeholder"><div className="ai-orb large"><BrainCircuit/></div><b>让数据告诉你，为什么交易。</b><span>Quant Engine 提供评分、风险和目标权重，助手将它们翻译成自然语言。</span></div>}</Card></div><Card><PanelHeader title="AI 使用边界" subtitle="系统安全原则"/><div className="guardrail-grid"><div><b>只解释，不下单</b><span>LLM 不产生目标权重，也不会绕过风险控制。</span></div><div><b>数据有来源</b><span>解释上下文来自因子和交易账本，避免凭空编造。</span></div><div><b>可选外部模型</b><span>配置 OpenAI-compatible Key 后，可升级为 LLM 研究摘要。</span></div></div></Card>{mutation.isError && <Toast message="解释生成失败" type="error"/>}</>
}

