import { useQuery } from '@tanstack/react-query'
import { Activity, ArrowUpRight, BriefcaseBusiness, Gauge, Landmark, LineChart, ShieldAlert, WalletCards } from 'lucide-react'
import { api, formatMoney, formatPercent } from '../api'
import { BarChart, DrawdownChart, EquityChart, PieChart } from '../components/Charts'
import { Card, ErrorState, LoadingState, MetricCard, PanelHeader, SignalBadge } from '../components/UI'

export function Dashboard() {
  const { data, isLoading, isError } = useQuery({ queryKey: ['dashboard'], queryFn: async () => (await api.get('/dashboard')).data, refetchInterval: 30_000 })
  if (isLoading) return <LoadingState />
  if (isError || !data) return <ErrorState />
  const account = data.account
  const metrics = data.backtest_metrics || {}
  const returnTone = account.cumulative_return >= 0 ? 'positive' : 'negative'
  return <>
    {/* 通用目录的Demo/Real状态已经在下面"系统状态"卡片的Data Adapter
        那一行显示了，这里不再重复放一个徽标。 */}
    <div className="dashboard-hero"><div><span className="eyebrow">OVERVIEW / 01</span><h1>投资驾驶舱</h1><p>把长期主义，变成可验证的资产增长路径。</p></div><div className="hero-meta"><span>数据截止 {data.as_of}</span></div></div>
    <div className="metric-grid"><MetricCard label="总资产" value={formatMoney(account.total_assets)} change={`${formatPercent(account.cumulative_return)} 累计`} tone={returnTone} icon={<WalletCards size={18}/>} /><MetricCard label="策略年化收益" value={formatPercent(metrics.annual_return)} change="回测结果" tone={metrics.annual_return >= 0 ? 'positive' : 'negative'} icon={<LineChart size={18}/>} /><MetricCard label="最大回撤" value={formatPercent(metrics.max_drawdown)} change="风险观察" tone="negative" icon={<ShieldAlert size={18}/>} /><MetricCard label="Sharpe Ratio" value={(metrics.sharpe || 0).toFixed(2)} change="风险调整后收益" icon={<Gauge size={18}/>} /><MetricCard label="可用现金" value={formatMoney(account.cash)} change={`${formatPercent(account.cash / account.total_assets)} 资产占比`} icon={<Landmark size={18}/>} /></div>
    <div className="dashboard-grid"><Card className="chart-card span-8"><PanelHeader title="策略净值" subtitle="低频价值成长 V1 · 对比沪深 300 · BUY/SELL 点来自实际成交" action={<div className="chart-legend"><span><i className="legend-dot mint"/>策略</span><span><i className="legend-dot blue"/>沪深300</span></div>} />{data.equity?.length ? <EquityChart data={data.equity} trades={data.trade_markers || []}/> : <div className="empty-chart">运行一次回测后，净值曲线会显示在这里。</div>}</Card><Card className="span-4"><PanelHeader title="组合快照" subtitle="当前模拟盘" /><div className="portfolio-summary"><div><span>持仓市值</span><strong>{formatMoney(account.market_value)}</strong></div><div><span>今日收益</span><strong className={account.daily_return >= 0 ? 'text-mint' : 'text-rose'}>{formatPercent(account.daily_return)}</strong></div><div><span>持仓数量</span><strong>{account.positions.length}<small> / 10</small></strong></div></div><div className="mini-positions">{account.positions.slice(0, 4).map((p: any) => <div className="mini-position" key={p.symbol}><div className="stock-avatar">{p.symbol.slice(-2)}</div><div><b>{p.symbol}</b><span>{p.quantity} 股</span></div><strong className={p.pnl >= 0 ? 'text-mint' : 'text-rose'}>{formatPercent(p.pnl_pct)}</strong></div>)}{!account.positions.length && <div className="muted-empty">模拟盘暂时没有持仓</div>}</div></Card></div>
    <div className="dashboard-grid"><Card className="span-8"><PanelHeader title="最新交易信号" subtitle="来自当前策略评分和风险约束" action={<a className="text-link" href="/stocks">查看股票池 <ArrowUpRight size={14}/></a>} /><div className="table-wrap"><table><thead><tr><th>股票</th><th>行业</th><th>评分</th><th>12M 动量</th><th>目标权重</th><th>信号</th></tr></thead><tbody>{data.signals.slice(0, 6).map((row: any) => <tr key={row.symbol}><td><div className="stock-cell"><div className="stock-avatar">{row.symbol.slice(-2)}</div><div><b>{row.name}</b><span>{row.symbol}</span></div></div></td><td>{row.industry}</td><td><b>{row.score.toFixed(1)}</b><div className="score-bar"><i style={{width: `${row.score}%`}}/></div></td><td className={row.return_12m >= 0 ? 'text-mint' : 'text-rose'}>{formatPercent(row.return_12m)}</td><td>{formatPercent(row.target_weight)}</td><td><SignalBadge signal={row.action}/></td></tr>)}</tbody></table></div></Card><Card className="span-4"><PanelHeader title="最近交易" subtitle="Paper Trading 账本" />{data.recent_orders?.length ? <div className="order-list">{data.recent_orders.slice(0, 5).map((order: any) => <div className="order-item" key={order.id}><span className={`order-side ${order.side.toLowerCase()}`}>{order.side}</span><div><b>{order.symbol}</b><span>{order.quantity} 股 · {formatMoney(order.amount)}</span></div><time>{order.time?.slice(5, 16)}</time></div>)}</div> : <div className="muted-empty">暂无交易记录，前往自动交易执行一次调仓。</div>}</Card></div>
    <div className="dashboard-grid"><Card className="span-4"><PanelHeader title="行业分布" subtitle="当前股票池" /><PieChart data={data.analytics?.industry_distribution || []}/></Card><Card className="span-4"><PanelHeader title="回撤曲线" subtitle={`历史最大回撤 ${formatPercent(metrics.max_drawdown)}`} /><DrawdownChart data={data.equity || []}/></Card><Card className="span-4"><PanelHeader title="系统状态" subtitle="运行环境与数据链路" /><div className="system-list"><div><span className="status-pulse"/>Data Adapter<strong>{data.data_mode === 'real' ? 'Baostock Real' : data.data_mode === 'demo' ? 'Demo Provider' : data.data_mode}</strong></div><div><span className="status-pulse mint"/>Quant Engine<strong>Ready</strong></div><div><span className="status-pulse blue"/>Paper Broker<strong>Connected</strong></div><div><span className="status-pulse gold"/>AI Research<strong>Rules Fallback</strong></div></div></Card></div>
  </>
}
